# Generated by Django 4.2.6 on 2023-10-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reactif', models.CharField(max_length=26)),
                ('produit', models.CharField(max_length=26)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
