# Generated by Django 4.1 on 2023-10-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polymere', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='produit',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='reactif',
            field=models.CharField(max_length=500),
        ),
    ]
