# Generated by Django 4.1 on 2023-10-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polymere', '0002_alter_reaction_produit_alter_reaction_reactif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polymer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polymer', models.CharField(max_length=128)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Reaction',
        ),
    ]
