# Generated by Django 4.1 on 2023-10-28 21:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polymere', '0003_polymer_delete_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='polymer',
            name='timestamp_end',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
