# Generated by Django 4.1 on 2023-10-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polymere', '0005_alter_polymer_polymer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polymer',
            name='polymer',
            field=models.CharField(max_length=128),
        ),
    ]
