# Generated by Django 4.1 on 2023-10-29 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polymere', '0006_alter_polymer_polymer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polymer',
            old_name='timestamp_end',
            new_name='end_time',
        ),
    ]
